# Done to support IDEs (this is unnecessary in a production environment)
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=com.mccpvptl
archives_base_name=mccpvptiertagger

# Dependencies
fabric_version=0.107.0+1.21.11
